name: Build Python Executable

# 这个工作流会在你推送到 main 分支时触发
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # 我们将在一个 Windows 环境中运行
    runs-on: windows-latest

    steps:
    # 第一步：检出你的代码
    - uses: actions/checkout@v3

    # 第二步：设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # 使用一个兼容的 Python 版本

    # 第三步：安装依赖
    # 它会使用你的 requirements_v2.txt 文件
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_v2.txt
        pip install pyinstaller

    # 第四步：使用 PyInstaller 构建 EXE
    # 这里我们假设你的主程序入口是 whisk_launcher_v2.py
    - name: Build executable with PyInstaller
      run: pyinstaller --onefile --windowed whisk_launcher_v2.py

    # 第五步：上传构建好的 EXE 文件
    # 构建完成后，你可以在 "Actions" 页面的对应运行记录中找到这个名为 "windows-executable" 的产物
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: dist/whisk_launcher_v2.exe
